### ISSUE TITLE
[DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.

### ISSUE THREAD

**Issue by wzalazar** [Microsoft/vscode-recipes#28]

**Comment by auchenberg** [comment]
@wzalazar Which recipe are you using?

**Comment by wzalazar** [comment]
HI @auchenberg , I'm using docker + typescript. I'm trying different configurations, because any works fine. 

I'm using node 8.1.4

**Comment by auchenberg** [comment]
@weinand @roblourens Haven't we fixed this recently?

**Comment by roblourens** [comment]
Yes in 1.17

**Comment by auchenberg** [comment]
@wzalazar This will be fixed in the upcoming release of VS Code.

**Comment by wzalazar** [comment]
I'm using VS code 1.16.1, I will update now.  Thanks @auchenberg , @roblourens

**Comment by vishalpwankhede** [comment]
Hi,
I am using already latest VS code version

Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:41:01.414Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Still facing issue while debugging. Any suggestions

**Comment by weinand** [comment]
@vishalpwankhede please create a new issue and describe your problem with repeatable steps.
